#!/bin/bash
is_prime() {
 n=$1
 if [ $n -le 1 ]; then
 echo "Not Prime"
 return
 fi
 for ((i=2; i*i<=n; i++)); do
 if [ $((n%i)) -eq 0 ]; then
 echo "Not Prime"
 return
 fi
 done
 echo "Prime"
}
is_leap() {
 y=$1
 if (( (y%4==0 && y%100!=0) || (y%400==0) )); then
echo "Leap Year"
 else
 echo "Not Leap Year"
 fi
}
sum_series() {
 n=$1
 sum=0
 for ((i=1;i<=n;i++)); do
 sum=$((sum+i))
 done
 echo "Sum = $sum"
}
echo "1. Check Prime"
echo "2. Check Leap Year"
echo "3. Sum of Series"
echo "4. Exit"
read -p "Enter choice: " ch
case $ch in
1) read -p "Enter number: " n
 is_prime $n ;;
2) read -p "Enter year: " y
 is_leap $y ;;
3) read -p "Enter n: " n
 sum_series $n ;;
4) exit ;;
*) echo "Invalid choice" ;;
esac
